[versions]
hiltAndroidCompilerVersion = "2.40.5"
hiltAndroidVersion = "2.40.5"
minSdk = "26"
compileSdk = "34"

coilComposeVersion = "2.5.0"
ktorVersion = "2.3.6"
agpVersion = "8.3.2"
kotlin = "2.0.0"
composeBomVersion = "2024.09.03"
navVersion = "2.8.9"
activityComposeVersion = "1.9.0"
coreKtxVersion = "1.13.1"
lifecycleRuntimeKtxVersion = "2.8.2"

espressoCoreVersion = "3.5.1"
junit = "1.1.5"
junitVersion = "4.13.2"
uiGraphicsAndroidVersion = "1.7.8"
appcompatVersion = "1.7.0"
materialVersion = "1.12.0"
jetbrainsKotlinJvmVersion = "2.0.0"

serialization = "1.6.3"
ksp = "2.0.21-1.0.25"

[libraries]
# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
# Android
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
# Testing
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroidVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agpVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agpVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvmVersion" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
compose = [
    "compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "compose-material3", "compose-foundation"
]
ktor = [
    "ktor-client-core", "ktor-client-okhttp", "ktor-client-logging",
    "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"
]
